apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarBroker
metadata:
  name: pulsar
  namespace: pulsar
spec:
  image: streamnative/pulsar:2.10.3.3
  pod:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
    terminationGracePeriodSeconds: 30
  jvmOptions:
    extraOptions:
    -  -Dpulsar.allocator.exit_on_oom=true
    -  -Dio.netty.recycler.maxCapacityPerThread=4096
    PULSAR_LOG_LEVEL: "debug"
    PULSAR_LOG_ROOT_LEVEL: "debug"
  config:
    custom:
      webSocketServiceEnabled: "true"
  replicas: 3
  zkServers: zookeeper-zk-headless:2181
