apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarProxy
metadata:
    name: my
    namespace: pulsar
spec:
    brokerAddress: my-broker-headless
    dnsNames: []
    #webSocketServiceEnabled: true
    image: streamnative/pulsar:2.9.2.17
    config:
      tls:
        enabled: false
    issuerRef:
      name: ""
    pod:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    replicas: 1
