apiVersion: zookeeper.streamnative.io/v1alpha1
kind: ZooKeeperCluster
metadata:
  name: zookeeper
  namespace: pulsar
spec:
  image: streamnative/pulsar:2.10.2.4
  replicas: 3
  pod:
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
  persistence:
    reclaimPolicy: Retain
    data:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "5Gi"
    dataLog:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "10Gi"
